### ISSUE TITLE
Get a shorter domain name for the URL shortener

### ISSUE THREAD

**Issue by anonsubmitter** [andreGarvin/openkey#1]
This looks really nice, but I think it needs a shorter domain name than openkey.herokuapp.com for the short links. Openkey.link is still available, for example ($7.69 on NameSilo if you use a promo code like 1FREE).

**Comment by andreGarvin** [comment]
hey, @anonsubmitter  wow I did not think people actually used this website but I can do that today just been busy a lot of things.
Can you send me a link to the website and the domain name ?

**Comment by anonsubmitter** [comment]
Sorry about the delay. Yeah, I found the site when Shoutkey was down and I like that OpenKey doesn't use Google's reCAPTCHA (those are a pain in the ass) and that it doesn't use Google Analytics.

[Porkbun](https://porkbun.com/) is seems to be [the](https://tld-list.com/registrars/porkbun) highest [rated](https://www.domcomp.com/reviews/porkbun) domain registrar, so I'd give that one a try.

**Comment by andreGarvin** [comment]
Okay. Thanks by the way I did not know anyone was using the site tbh, this is really a shocker.

I am thinking about converting openkey to a node app on the backend instead of a python flask and using vue.js for the frontend. You are welcome to contribute if you like.
